// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientserver.proto

#ifndef PROTOBUF_INCLUDED_clientserver_2eproto
#define PROTOBUF_INCLUDED_clientserver_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_clientserver_2eproto 

namespace protobuf_clientserver_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_clientserver_2eproto
namespace assignment {
class messageinfo;
class messageinfoDefaultTypeInternal;
extern messageinfoDefaultTypeInternal _messageinfo_default_instance_;
}  // namespace assignment
namespace google {
namespace protobuf {
template<> ::assignment::messageinfo* Arena::CreateMaybeMessage<::assignment::messageinfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace assignment {

// ===================================================================

class messageinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:assignment.messageinfo) */ {
 public:
  messageinfo();
  virtual ~messageinfo();

  messageinfo(const messageinfo& from);

  inline messageinfo& operator=(const messageinfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  messageinfo(messageinfo&& from) noexcept
    : messageinfo() {
    *this = ::std::move(from);
  }

  inline messageinfo& operator=(messageinfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const messageinfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const messageinfo* internal_default_instance() {
    return reinterpret_cast<const messageinfo*>(
               &_messageinfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(messageinfo* other);
  friend void swap(messageinfo& a, messageinfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline messageinfo* New() const final {
    return CreateMaybeMessage<messageinfo>(NULL);
  }

  messageinfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<messageinfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const messageinfo& from);
  void MergeFrom(const messageinfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(messageinfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string txtmessage = 1;
  void clear_txtmessage();
  static const int kTxtmessageFieldNumber = 1;
  const ::std::string& txtmessage() const;
  void set_txtmessage(const ::std::string& value);
  #if LANG_CXX11
  void set_txtmessage(::std::string&& value);
  #endif
  void set_txtmessage(const char* value);
  void set_txtmessage(const char* value, size_t size);
  ::std::string* mutable_txtmessage();
  ::std::string* release_txtmessage();
  void set_allocated_txtmessage(::std::string* txtmessage);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // bool flg = 3;
  void clear_flg();
  static const int kFlgFieldNumber = 3;
  bool flg() const;
  void set_flg(bool value);

  // @@protoc_insertion_point(class_scope:assignment.messageinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr txtmessage_;
  ::google::protobuf::int32 id_;
  bool flg_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_clientserver_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// messageinfo

// string txtmessage = 1;
inline void messageinfo::clear_txtmessage() {
  txtmessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& messageinfo::txtmessage() const {
  // @@protoc_insertion_point(field_get:assignment.messageinfo.txtmessage)
  return txtmessage_.GetNoArena();
}
inline void messageinfo::set_txtmessage(const ::std::string& value) {
  
  txtmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:assignment.messageinfo.txtmessage)
}
#if LANG_CXX11
inline void messageinfo::set_txtmessage(::std::string&& value) {
  
  txtmessage_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:assignment.messageinfo.txtmessage)
}
#endif
inline void messageinfo::set_txtmessage(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  txtmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:assignment.messageinfo.txtmessage)
}
inline void messageinfo::set_txtmessage(const char* value, size_t size) {
  
  txtmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:assignment.messageinfo.txtmessage)
}
inline ::std::string* messageinfo::mutable_txtmessage() {
  
  // @@protoc_insertion_point(field_mutable:assignment.messageinfo.txtmessage)
  return txtmessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* messageinfo::release_txtmessage() {
  // @@protoc_insertion_point(field_release:assignment.messageinfo.txtmessage)
  
  return txtmessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void messageinfo::set_allocated_txtmessage(::std::string* txtmessage) {
  if (txtmessage != NULL) {
    
  } else {
    
  }
  txtmessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), txtmessage);
  // @@protoc_insertion_point(field_set_allocated:assignment.messageinfo.txtmessage)
}

// int32 id = 2;
inline void messageinfo::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 messageinfo::id() const {
  // @@protoc_insertion_point(field_get:assignment.messageinfo.id)
  return id_;
}
inline void messageinfo::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:assignment.messageinfo.id)
}

// bool flg = 3;
inline void messageinfo::clear_flg() {
  flg_ = false;
}
inline bool messageinfo::flg() const {
  // @@protoc_insertion_point(field_get:assignment.messageinfo.flg)
  return flg_;
}
inline void messageinfo::set_flg(bool value) {
  
  flg_ = value;
  // @@protoc_insertion_point(field_set:assignment.messageinfo.flg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace assignment

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_clientserver_2eproto
